server.port=8080
spring.application.name=api-gateway

# --- Spring Cloud Gateway Routes ---

# 1. Product Service
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/products/**

# 2. Discount (Routing to Product Service)
spring.cloud.gateway.routes[1].id=discount-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/discount/**

# 3. Price History (Routing to Product Service)
spring.cloud.gateway.routes[2].id=price-history-service
spring.cloud.gateway.routes[2].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/price-history/**

# 4. Order Service
spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/orders/**

# 5. Inventory Service
spring.cloud.gateway.routes[4].id=inventory-service
spring.cloud.gateway.routes[4].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/inventory/**

# --- Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# --- Critical: Hostname Resolve
eureka.instance.prefer-ip-address=true

# --- Logging for Troubleshooting
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG